### ISSUE TITLE
Error in dynamic routing

### ISSUE THREAD

**Issue by supernovahs** [supernovahs/ClickedZKvote-frontend#1]
When  this [link](https://zkvote.vercel.app/Vote/213697537779571221725060409790046191845798457011766795360602110051171459534)
is opened , the  [Vote](https://github.com/supernovahs/Zk-Voting-/blob/86fa638473986e3cdff1e1b4517e6797855da282/pages/Vote/%5BVote%5D.jsx#L14) variable 
does not load immediately, resulting in its value being undefined, hence the page does not load directly.
But when the link is opened using the [Open](https://github.com/supernovahs/Zk-Voting-/blob/86fa638473986e3cdff1e1b4517e6797855da282/pages/Activeproposals.jsx#L96) Button  it works fine .

**Comment by Dhaiwat10** [comment]
Can take this on! @supernovahs
