### ISSUE TITLE
Homepage rendering bugs

### ISSUE THREAD

**Issue by supernovahs** [supernovahs/ClickedZKvote-frontend#2]
React bugs in index.txs
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
Warning: Expected server HTML to contain a matching li tag in p tag

**Comment by Dhaiwat10** [comment]
Classic error, can take this on as well
